package java10x.EventClean.infra.exception;

import java10x.EventClean.core.entities.Evento;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

import java.util.HashMap;
import java.util.Map;

@RestControllerAdvice
public class ControllerExceptionHandler {

    @ExceptionHandler(DuplicateEventException.class)
    public ResponseEntity<Map<String, String>> handleDuplicateEventException(DuplicateEventException exc) {
        Map<String, String> response = new HashMap<>();
        response.put("Error: ", exc.getMessage());
        response.put("Message: ", "Please, insert a valid hashId for your event and try again!");

        return new ResponseEntity<>(response, HttpStatus.CONFLICT);
    }

    @ExceptionHandler(EventNotExistsException.class)
    public ResponseEntity<Map<String, String>> handleEventNotExistsException(EventNotExistsException exc) {
        Map<String, String> response = new HashMap<>();
        response.put("Error: ", exc.getMessage());
        response.put("Message: ", "The request event was not found, check the identifier and try again.");

        return new ResponseEntity<>(response, HttpStatus.NOT_FOUND);
    }

    @ExceptionHandler(ManualIdentifierNotAllowedException.class)
    public ResponseEntity<Map<String, String>> handleManualIdentifierNotAllowedException(ManualIdentifierNotAllowedException exc) {
        Map<String, String> response = new HashMap<>();
        response.put("Error: ", exc.getMessage());
        response.put("Message: ", "The identifier is automatically generated by the system and should not be sent!");

        return new ResponseEntity<>(response, HttpStatus.UNPROCESSABLE_CONTENT);
    }

}
