#1 nome da acao
name: Build and deploy of EventCleanApi v1

#2 gatilho da acao
on:
  push:
    branches: [main]

#3 acao
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Java
        uses: actions/setup-java@v3
        with:
          java-versionL: 17
          distribution: 'temurin'

      - name: Checkout code
        run: mvn clean install